services:
  test:
    profiles: [test]
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    command:
    - sh
    - -cx
    - |
      alembic downgrade base &&
      alembic upgrade head &&
      python -m pytest
    env_file: .env.test-docker
    volumes:
    - ./tests:/code/tests
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    profiles: [test]
    image: pgvector/pgvector:0.8.0-pg17-trixie
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
    ports:
    - "127.0.0.1:5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
      start_interval: 2s
    restart: "no"
    command:  # see https://www.postgresql.org/docs/current/non-durability.html
    - postgres
    - -cfsync=off
    - -csynchronous_commit=off
    - -cfull_page_writes=off
    #- -clog_statement=all
