"""Web api."""

from fastapi import APIRouter, Depends

from app.dependencies.auth import user_verified
from app.routers import (
    asset,
    brain_atlas,
    brain_region,
    brain_region_hierarchy,
    cell_composition,
    circuit,
    contribution,
    derivation,
    electrical_cell_recording,
    emodel,
    entity,
    etype,
    etype_classification,
    experimental_bouton_density,
    experimental_neuron_density,
    experimental_synapses_per_connection,
    ion_channel_model,
    license,
    measurement_annotation,
    memodel,
    memodel_calibration_result,
    morphology,
    mtype,
    mtype_classification,
    organization,
    person,
    publication,
    role,
    root,
    simulation,
    simulation_campaign,
    simulation_execution,
    simulation_generation,
    simulation_result,
    single_neuron_simulation,
    single_neuron_synaptome,
    single_neuron_synaptome_simulation,
    species,
    strain,
    subject,
    validation_result,
)

router = APIRouter()
router.include_router(root.router)
authenticated_routers = [
    asset.router,
    brain_atlas.router,
    brain_region.router,
    brain_region_hierarchy.router,
    cell_composition.router,
    circuit.router,
    contribution.router,
    derivation.router,
    electrical_cell_recording.router,
    emodel.router,
    entity.router,
    etype.router,
    etype_classification.router,
    experimental_bouton_density.router,
    experimental_neuron_density.router,
    experimental_synapses_per_connection.router,
    ion_channel_model.router,
    license.router,
    measurement_annotation.router,
    memodel.router,
    memodel_calibration_result.router,
    morphology.router,
    mtype.router,
    mtype_classification.router,
    organization.router,
    person.router,
    publication.router,
    role.router,
    simulation.router,
    simulation_campaign.router,
    simulation_execution.router,
    simulation_generation.router,
    simulation_result.router,
    single_neuron_simulation.router,
    single_neuron_synaptome.router,
    single_neuron_synaptome_simulation.router,
    species.router,
    strain.router,
    subject.router,
    validation_result.router,
]
for r in authenticated_routers:
    router.include_router(r, dependencies=[Depends(user_verified)])
