"""agents

Revision ID: 161db3044e12
Revises: 19e6c28114fa
Create Date: 2025-05-15 17:30:57.331843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "161db3044e12"
down_revision: Union[str, None] = "19e6c28114fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("person", sa.Column("subject_id", sa.Uuid(), nullable=True))
    op.alter_column("person", "givenName", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("person", "familyName", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_person_subject_id"), "person", ["subject_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_person_subject_id"), table_name="person")
    op.alter_column("person", "familyName", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("person", "givenName", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("person", "subject_id")
    # ### end Alembic commands ###
