"""Default migration message

Revision ID: 536447d03afe
Revises: e3c7dd45bc79
Create Date: 2025-06-07 15:02:56.350515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "536447d03afe"
down_revision: Union[str, None] = "e3c7dd45bc79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulation", sa.Column("name", sa.String(), nullable=False))
    op.add_column("simulation", sa.Column("description", sa.String(), nullable=False))
    op.add_column(
        "simulation", sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "ix_simulation_description_vector",
        "simulation",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_simulation_name"), "simulation", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulation_name"), table_name="simulation")
    op.drop_index(
        "ix_simulation_description_vector", table_name="simulation", postgresql_using="gin"
    )
    op.drop_column("simulation", "description_vector")
    op.drop_column("simulation", "description")
    op.drop_column("simulation", "name")
    # ### end Alembic commands ###
