"""Default migration message

Revision ID: 55c08bba29ef
Revises: a45638c6f52a
Create Date: 2025-04-30 15:13:30.190695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "55c08bba29ef"
down_revision: Union[str, None] = "a45638c6f52a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cell_composition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("brain_region_id", sa.BigInteger(), nullable=False),
        sa.Column("species_id", sa.Uuid(), nullable=False),
        sa.Column("strain_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brain_region_id"],
            ["brain_region.id"],
            name=op.f("fk_cell_composition_brain_region_id_brain_region"),
        ),
        sa.ForeignKeyConstraint(["id"], ["entity.id"], name=op.f("fk_cell_composition_id_entity")),
        sa.ForeignKeyConstraint(
            ["species_id"], ["species.id"], name=op.f("fk_cell_composition_species_id_species")
        ),
        sa.ForeignKeyConstraint(
            ["strain_id", "species_id"],
            ["strain.id", "strain.species_id"],
            name="fk_cell_composition_strain_id_species_id",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cell_composition")),
    )
    op.create_index(
        op.f("ix_cell_composition_brain_region_id"),
        "cell_composition",
        ["brain_region_id"],
        unique=False,
    )
    op.create_index(
        "ix_cell_composition_description_vector",
        "cell_composition",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_cell_composition_name"), "cell_composition", ["name"], unique=False)
    op.create_index(
        op.f("ix_cell_composition_species_id"), "cell_composition", ["species_id"], unique=False
    )
    op.create_index(
        op.f("ix_cell_composition_strain_id"), "cell_composition", ["strain_id"], unique=False
    )
    op.create_table(
        "me_type_density",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("brain_region_id", sa.BigInteger(), nullable=False),
        sa.Column("species_id", sa.Uuid(), nullable=False),
        sa.Column("strain_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brain_region_id"],
            ["brain_region.id"],
            name=op.f("fk_me_type_density_brain_region_id_brain_region"),
        ),
        sa.ForeignKeyConstraint(["id"], ["entity.id"], name=op.f("fk_me_type_density_id_entity")),
        sa.ForeignKeyConstraint(
            ["species_id"], ["species.id"], name=op.f("fk_me_type_density_species_id_species")
        ),
        sa.ForeignKeyConstraint(
            ["strain_id", "species_id"],
            ["strain.id", "strain.species_id"],
            name="fk_me_type_density_strain_id_species_id",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_me_type_density")),
    )
    op.create_index(
        op.f("ix_me_type_density_brain_region_id"),
        "me_type_density",
        ["brain_region_id"],
        unique=False,
    )
    op.create_index(
        "ix_me_type_density_description_vector",
        "me_type_density",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_me_type_density_name"), "me_type_density", ["name"], unique=False)
    op.create_index(
        op.f("ix_me_type_density_species_id"), "me_type_density", ["species_id"], unique=False
    )
    op.create_index(
        op.f("ix_me_type_density_strain_id"), "me_type_density", ["strain_id"], unique=False
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "age",
            "analysis_software_source_code",
            "emodel",
            "cell_composition",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "memodel",
            "mesh",
            "me_type_density",
            "reconstruction_morphology",
            "electrical_cell_recording",
            "electrical_recording_stimulus",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "ion_channel_model",
            "subject",
            "synaptic_pathway",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "age",
            "analysis_software_source_code",
            "emodel",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "memodel",
            "mesh",
            "reconstruction_morphology",
            "electrical_cell_recording",
            "electrical_recording_stimulus",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "ion_channel_model",
            "subject",
            "synaptic_pathway",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f("ix_me_type_density_strain_id"), table_name="me_type_density")
    op.drop_index(op.f("ix_me_type_density_species_id"), table_name="me_type_density")
    op.drop_index(op.f("ix_me_type_density_name"), table_name="me_type_density")
    op.drop_index(
        "ix_me_type_density_description_vector",
        table_name="me_type_density",
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_me_type_density_brain_region_id"), table_name="me_type_density")
    op.drop_table("me_type_density")
    op.drop_index(op.f("ix_cell_composition_strain_id"), table_name="cell_composition")
    op.drop_index(op.f("ix_cell_composition_species_id"), table_name="cell_composition")
    op.drop_index(op.f("ix_cell_composition_name"), table_name="cell_composition")
    op.drop_index(
        "ix_cell_composition_description_vector",
        table_name="cell_composition",
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_cell_composition_brain_region_id"), table_name="cell_composition")
    op.drop_table("cell_composition")
    # ### end Alembic commands ###
