"""Default migration message

Revision ID: f79522af5f30
Revises: 44f45ebae259
Create Date: 2025-04-10 19:57:06.373302

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f79522af5f30"
down_revision: str | None = "44f45ebae259"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="measurementunit",
        new_values=["dimensionless", "cell_density"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="measurement_record", column_name="unit"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="measurementunit",
        new_values=["dimensionless"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="measurement_record", column_name="unit"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
