"""Currents

Revision ID: 19e6c28114fa
Revises: dc7e28e7d8f6
Create Date: 2025-05-14 16:34:57.859900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "19e6c28114fa"
down_revision: Union[str, None] = "dc7e28e7d8f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memodel", sa.Column("holding_current", sa.Float(), nullable=True))
    op.add_column("memodel", sa.Column("threshold_current", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memodel", "threshold_current")
    op.drop_column("memodel", "holding_current")
    # ### end Alembic commands ###
