"""IonChannelModel

Revision ID: 82d121a0be58
Revises: 58a94baa91bc
Create Date: 2025-04-30 10:38:28.017057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "82d121a0be58"
down_revision: Union[str, None] = "58a94baa91bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ion", sa.Column("ontology_id", sa.String(), nullable=False))
    op.create_index(op.f("ix_ion_ontology_id"), "ion", ["ontology_id"], unique=True)
    op.add_column("ion_channel_model", sa.Column("nmodl_suffix", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ion_channel_model", "nmodl_suffix")
    op.drop_index(op.f("ix_ion_ontology_id"), table_name="ion")
    op.drop_column("ion", "ontology_id")
    # ### end Alembic commands ###
