"""Default migration message

Revision ID: 9730c55381f3
Revises: b8490e92310f
Create Date: 2025-05-21 13:18:02.105223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "9730c55381f3"
down_revision: Union[str, None] = "b8490e92310f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("validated_entity_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["entity.id"], name=op.f("fk_validation_result_id_entity")),
        sa.ForeignKeyConstraint(
            ["validated_entity_id"],
            ["entity.id"],
            name=op.f("fk_validation_result_validated_entity_id_entity"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_result")),
    )
    op.create_index(op.f("ix_validation_result_name"), "validation_result", ["name"], unique=False)
    op.create_index(
        op.f("ix_validation_result_validated_entity_id"),
        "validation_result",
        ["validated_entity_id"],
        unique=False,
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "analysis_software_source_code",
            "brain_atlas",
            "emodel",
            "cell_composition",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "memodel",
            "mesh",
            "me_type_density",
            "reconstruction_morphology",
            "electrical_cell_recording",
            "electrical_recording_stimulus",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "ion_channel_model",
            "subject",
            "validation_result",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "analysis_software_source_code",
            "brain_atlas",
            "emodel",
            "cell_composition",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "memodel",
            "mesh",
            "me_type_density",
            "reconstruction_morphology",
            "electrical_cell_recording",
            "electrical_recording_stimulus",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "ion_channel_model",
            "subject",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f("ix_validation_result_validated_entity_id"), table_name="validation_result")
    op.drop_index(op.f("ix_validation_result_name"), table_name="validation_result")
    op.drop_table("validation_result")
    # ### end Alembic commands ###
