"""Default migration message

Revision ID: 78a062bf2eb5
Revises: e5664e5eee78
Create Date: 2025-06-19 10:00:40.058439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "78a062bf2eb5"
down_revision: Union[str, None] = "e5664e5eee78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulation_result", sa.Column("simulation_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_simulation_result_simulation_id"),
        "simulation_result",
        ["simulation_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_simulation_result_simulation_id_simulation"),
        "simulation_result",
        "simulation",
        ["simulation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_simulation_result_simulation_id_simulation"),
        "simulation_result",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_simulation_result_simulation_id"), table_name="simulation_result")
    op.drop_column("simulation_result", "simulation_id")
    # ### end Alembic commands ###
