"""Default migration message

Revision ID: 3bb17e1231d6
Revises: 7182cf8f7b50
Create Date: 2025-03-31 12:44:17.332353

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bb17e1231d6"
down_revision: str | None = "7182cf8f7b50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("license", sa.Column("pref_label", sa.String(), nullable=False))
    op.add_column("license", sa.Column("alt_label", sa.String(), nullable=True))
    op.drop_index("ix_license_name", table_name="license")
    op.create_index(op.f("ix_license_pref_label"), "license", ["pref_label"], unique=True)
    op.drop_column("license", "name")
    op.drop_column("license", "label")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("license", sa.Column("label", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("license", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_license_pref_label"), table_name="license")
    op.create_index("ix_license_name", "license", ["name"], unique=True)
    op.drop_column("license", "alt_label")
    op.drop_column("license", "pref_label")
    # ### end Alembic commands ###
