"""Default migration message

Revision ID: e5664e5eee78
Revises: 538e8640be55
Create Date: 2025-06-16 13:31:33.640118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "e5664e5eee78"
down_revision: Union[str, None] = "538e8640be55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etype_classification", sa.Column("authorized_project_id", sa.Uuid(), nullable=False)
    )
    op.add_column(
        "etype_classification", sa.Column("authorized_public", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "mtype_classification", sa.Column("authorized_project_id", sa.Uuid(), nullable=False)
    )
    op.add_column(
        "mtype_classification", sa.Column("authorized_public", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mtype_classification", "authorized_public")
    op.drop_column("mtype_classification", "authorized_project_id")
    op.drop_column("etype_classification", "authorized_public")
    op.drop_column("etype_classification", "authorized_project_id")
    # ### end Alembic commands ###
