"""empty message

Revision ID: 6dac1d228a54
Revises: 989322c75e81
Create Date: 2025-01-29 09:15:29.407295

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dac1d228a54"
down_revision: str | None = "989322c75e81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("authorized_project_id", sa.UUID(), nullable=False))
    op.add_column("entity", sa.Column("authorized_public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "authorized_public")
    op.drop_column("entity", "authorized_project_id")
    # ### end Alembic commands ###
