"""Default migration message

Revision ID: b769bd7b4030
Revises: 55c08bba29ef
Create Date: 2025-04-30 15:13:59.460178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "b769bd7b4030"
down_revision: Union[str, None] = "55c08bba29ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_cell_composition_cell_composition_description_vector = PGTrigger(
        schema="public",
        signature="cell_composition_description_vector",
        on_entity="public.cell_composition",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON cell_composition\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_cell_composition_cell_composition_description_vector)

    public_me_type_density_me_type_density_description_vector = PGTrigger(
        schema="public",
        signature="me_type_density_description_vector",
        on_entity="public.me_type_density",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON me_type_density\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_me_type_density_me_type_density_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_me_type_density_me_type_density_description_vector = PGTrigger(
        schema="public",
        signature="me_type_density_description_vector",
        on_entity="public.me_type_density",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON me_type_density\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_me_type_density_me_type_density_description_vector)

    public_cell_composition_cell_composition_description_vector = PGTrigger(
        schema="public",
        signature="cell_composition_description_vector",
        on_entity="public.cell_composition",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON cell_composition\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_cell_composition_cell_composition_description_vector)

    # ### end Alembic commands ###
