"""Default migration message

Revision ID: 9b83c5914b27
Revises: fc2a6e745865
Create Date: 2025-04-08 18:22:03.017515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text

import app.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b83c5914b27"
down_revision: str | None = "fc2a6e745865"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_measurement_serie_element_measurement_id", table_name="measurement_serie_element"
    )
    op.drop_table("measurement_serie_element")
    op.drop_index("ix_measurement_measurement_of", table_name="measurement")
    op.drop_index("ix_measurement_morphology_feature_annotation_id", table_name="measurement")
    op.drop_table("measurement")
    op.add_column(
        "morphology_feature_annotation",
        sa.Column(
            "measurements",
            app.db.types.MeasurementCollectionType(astext_type=Text()),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("morphology_feature_annotation", "measurements")
    op.create_table(
        "measurement",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("measurement_of", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "morphology_feature_annotation_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["morphology_feature_annotation_id"],
            ["morphology_feature_annotation.id"],
            name="fk_measurement_morphology_feature_annotation_id_morphol_93f8",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_measurement"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_measurement_morphology_feature_annotation_id",
        "measurement",
        ["morphology_feature_annotation_id"],
        unique=False,
    )
    op.create_index(
        "ix_measurement_measurement_of", "measurement", ["measurement_of"], unique=False
    )
    op.create_table(
        "measurement_serie_element",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("measurement_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["measurement_id"],
            ["measurement.id"],
            name="fk_measurement_serie_element_measurement_id_measurement",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_measurement_serie_element"),
    )
    op.create_index(
        "ix_measurement_serie_element_measurement_id",
        "measurement_serie_element",
        ["measurement_id"],
        unique=False,
    )
    # ### end Alembic commands ###
