"""Default migration message

Revision ID: 269f145246ad
Revises: b769bd7b4030
Create Date: 2025-05-02 16:29:40.094892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "269f145246ad"
down_revision: Union[str, None] = "b769bd7b4030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brain_atlas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("brain_region_id", sa.BigInteger(), nullable=False),
        sa.Column("species_id", sa.Uuid(), nullable=False),
        sa.Column("strain_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brain_region_id"],
            ["brain_region.id"],
            name=op.f("fk_brain_atlas_brain_region_id_brain_region"),
        ),
        sa.ForeignKeyConstraint(["id"], ["entity.id"], name=op.f("fk_brain_atlas_id_entity")),
        sa.ForeignKeyConstraint(
            ["species_id"], ["species.id"], name=op.f("fk_brain_atlas_species_id_species")
        ),
        sa.ForeignKeyConstraint(
            ["strain_id", "species_id"],
            ["strain.id", "strain.species_id"],
            name="fk_brain_atlas_strain_id_species_id",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brain_atlas")),
    )
    op.create_index(
        op.f("ix_brain_atlas_brain_region_id"), "brain_atlas", ["brain_region_id"], unique=False
    )
    op.create_index(
        "ix_brain_atlas_description_vector",
        "brain_atlas",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_brain_atlas_name"), "brain_atlas", ["name"], unique=False)
    op.create_index(op.f("ix_brain_atlas_species_id"), "brain_atlas", ["species_id"], unique=False)
    op.create_index(op.f("ix_brain_atlas_strain_id"), "brain_atlas", ["strain_id"], unique=False)
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "analysis_software_source_code",
            "brain_atlas",
            "emodel",
            "cell_composition",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "memodel",
            "mesh",
            "me_type_density",
            "reconstruction_morphology",
            "electrical_cell_recording",
            "electrical_recording_stimulus",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "ion_channel_model",
            "subject",
            "synaptic_pathway",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "age",
            "analysis_software_source_code",
            "emodel",
            "cell_composition",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "memodel",
            "mesh",
            "me_type_density",
            "reconstruction_morphology",
            "electrical_cell_recording",
            "electrical_recording_stimulus",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "ion_channel_model",
            "subject",
            "synaptic_pathway",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f("ix_brain_atlas_strain_id"), table_name="brain_atlas")
    op.drop_index(op.f("ix_brain_atlas_species_id"), table_name="brain_atlas")
    op.drop_index(op.f("ix_brain_atlas_name"), table_name="brain_atlas")
    op.drop_index(
        "ix_brain_atlas_description_vector", table_name="brain_atlas", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_brain_atlas_brain_region_id"), table_name="brain_atlas")
    op.drop_table("brain_atlas")
    # ### end Alembic commands ###
