"""Currents

Revision ID: 6bee9d9e2bc5
Revises: e9aeb1413bcb
Create Date: 2025-05-14 16:15:51.045962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "6bee9d9e2bc5"
down_revision: Union[str, None] = "e9aeb1413bcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memodel", sa.Column("holding_current", sa.Float(), nullable=True))
    op.add_column("memodel", sa.Column("threshold_current", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memodel", "threshold_current")
    op.drop_column("memodel", "holding_current")
    # ### end Alembic commands ###
