"""agents

Revision ID: c6584fab20c1
Revises: 19e6c28114fa
Create Date: 2025-05-16 07:48:44.913397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "c6584fab20c1"
down_revision: Union[str, None] = "19e6c28114fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("person", sa.Column("given_name", sa.String(), nullable=True))
    op.add_column("person", sa.Column("family_name", sa.String(), nullable=True))
    op.add_column("person", sa.Column("subject_id", sa.Uuid(), nullable=True))
    op.drop_constraint("unique_person_name_1", "person", type_="unique")
    op.create_unique_constraint("unique_person_name_1", "person", ["given_name", "family_name"])
    op.create_index(op.f("ix_person_subject_id"), "person", ["subject_id"], unique=True)
    op.drop_column("person", "givenName")
    op.drop_column("person", "familyName")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person", sa.Column("familyName", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "person", sa.Column("givenName", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_person_subject_id"), table_name="person")
    op.drop_constraint("unique_person_name_1", "person", type_="unique")
    op.create_unique_constraint("unique_person_name_1", "person", ["givenName", "familyName"])
    op.drop_column("person", "subject_id")
    op.drop_column("person", "family_name")
    op.drop_column("person", "given_name")
    # ### end Alembic commands ###
