"""memodel enum status

Revision ID: 9a3d0f1be71b
Revises: f306642ba978
Create Date: 2025-03-19 19:42:45.685059

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a3d0f1be71b"
down_revision: str | None = "f306642ba978"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="me_model_validation_status",
        new_values=["created", "initialized", "running", "done", "error"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="memodel", column_name="validation_status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="me_model_validation_status",
        new_values=["CREATED", "INITIALIZED", "RUNNING", "DONE", "ERROR"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="memodel", column_name="validation_status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
