"""Add triggers for external_url

Revision ID: 80139d43afaf
Revises: 34a01809b4d4
Create Date: 2025-08-20 10:54:25.908534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "80139d43afaf"
down_revision: Union[str, None] = "34a01809b4d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_external_url_external_url_description_vector = PGTrigger(
        schema="public",
        signature="external_url_description_vector",
        on_entity="public.external_url",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON external_url\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_external_url_external_url_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_external_url_external_url_description_vector = PGTrigger(
        schema="public",
        signature="external_url_description_vector",
        on_entity="public.external_url",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON external_url\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_external_url_external_url_description_vector)

    # ### end Alembic commands ###
