"""empty message

Revision ID: c99dc0eb24b2
Revises: f8309e5aa4de
Create Date: 2025-03-18 12:07:22.434181

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c99dc0eb24b2"
down_revision: str | None = "f8309e5aa4de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("single_neuron_simulation", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("single_neuron_simulation", "status")
    # ### end Alembic commands ###
