"""Switch BrainRegion to align with contents of hierarchy

Revision ID: 87634ff81363
Revises: 989322c75e81
Create Date: 2025-01-31 13:19:17.387942

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87634ff81363"
down_revision: str | None = "989322c75e81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brain_region", sa.Column("acronym", sa.String(), nullable=False))
    op.add_column(
        "brain_region", sa.Column("children", postgresql.ARRAY(sa.BigInteger()), nullable=True)
    )
    op.alter_column(
        "brain_region",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('brain_region_id_seq'::regclass)"),
    )
    op.drop_index("ix_brain_region_ontology_id", table_name="brain_region")
    op.create_index(op.f("ix_brain_region_acronym"), "brain_region", ["acronym"], unique=True)
    op.drop_column("brain_region", "ontology_id")
    op.alter_column(
        "emodel",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_bouton_density",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_neuron_density",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_synapses_per_connection",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "memodel",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "mesh",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "reconstruction_morphology",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "single_cell_experimental_trace",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "single_neuron_simulation",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "single_neuron_synaptome",
        "brain_region_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "single_neuron_synaptome",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "single_neuron_simulation",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "single_cell_experimental_trace",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "reconstruction_morphology",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "mesh",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "memodel",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_synapses_per_connection",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_neuron_density",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "experimental_bouton_density",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "emodel",
        "brain_region_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.add_column(
        "brain_region", sa.Column("ontology_id", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_brain_region_acronym"), table_name="brain_region")
    op.create_index("ix_brain_region_ontology_id", "brain_region", ["ontology_id"], unique=True)
    op.alter_column(
        "brain_region",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('brain_region_id_seq'::regclass)"),
    )
    op.drop_column("brain_region", "children")
    op.drop_column("brain_region", "acronym")
    # ### end Alembic commands ###
