"""Default migration message

Revision ID: 85db275fb0e1
Revises: 1a5cec5b629b
Create Date: 2025-06-05 16:25:37.209591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "85db275fb0e1"
down_revision: Union[str, None] = "1a5cec5b629b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_circuit_circuit_description_vector = PGTrigger(
        schema="public",
        signature="circuit_description_vector",
        on_entity="public.circuit",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON circuit\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_circuit_circuit_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_circuit_circuit_description_vector = PGTrigger(
        schema="public",
        signature="circuit_description_vector",
        on_entity="public.circuit",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON circuit\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_circuit_circuit_description_vector)

    # ### end Alembic commands ###
