"""publication_reparenting

Revision ID: 48b86ee9a132
Revises: 8cd6f7bb6e36
Create Date: 2025-08-04 17:04:19.572119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "48b86ee9a132"
down_revision: Union[str, None] = "8cd6f7bb6e36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publication_DOI"), table_name="publication")
    op.drop_constraint(op.f("uq_publication_doi"), "publication", type_="unique")
    op.create_index(
        "ix_publication_doi_normalized",
        "publication",
        [sa.literal_column('lower("DOI")')],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_publication_doi_normalized", table_name="publication")
    op.create_unique_constraint(
        op.f("uq_publication_doi"), "publication", ["DOI"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("ix_publication_DOI"), "publication", ["DOI"], unique=False)
    # ### end Alembic commands ###
