"""Default migration message

Revision ID: 4b97a9affbf2
Revises: fb22746e4889
Create Date: 2025-07-17 21:22:00.705704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "4b97a9affbf2"
down_revision: Union[str, None] = "fb22746e4889"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_etype_per_entity", "etype_classification", ["entity_id", "etype_class_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_etype_per_entity", "etype_classification", type_="unique")
    # ### end Alembic commands ###
