"""Default migration message

Revision ID: eba7d0b636c5
Revises: b861d5b97dbe
Create Date: 2025-03-25 15:33:26.525419

"""

from collections.abc import Sequence

from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eba7d0b636c5"
down_revision: str | None = "b861d5b97dbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_single_neuron_synaptome_simulation_single_neuron_synaptome_simulation_description_vector = PGTrigger(
        schema="public",
        signature="single_neuron_synaptome_simulation_description_vector",
        on_entity="public.single_neuron_synaptome_simulation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON single_neuron_synaptome_simulation\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(
        public_single_neuron_synaptome_simulation_single_neuron_synaptome_simulation_description_vector
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_single_neuron_synaptome_simulation_single_neuron_synaptome_simulation_description_vector = PGTrigger(
        schema="public",
        signature="single_neuron_synaptome_simulation_description_vector",
        on_entity="public.single_neuron_synaptome_simulation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON single_neuron_synaptome_simulation\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(
        public_single_neuron_synaptome_simulation_single_neuron_synaptome_simulation_description_vector
    )

    # ### end Alembic commands ###
