"""Add 'SpeciesMixin' to 'BrainRegionHierarchy'

Revision ID: a5789f03b002
Revises: 6e114e5ca023
Create Date: 2025-12-08 13:15:34.443278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "a5789f03b002"
down_revision: Union[str, None] = "6e114e5ca023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    aibs_brain_hierarchy_id = "e3e70682-c209-4cac-a29f-6fbed82c07cd"
    mus_species_id = "b7ad4cca-4ac2-4095-9781-37fb68fe9ca1"

    op.add_column("brain_region_hierarchy", sa.Column("species_id", sa.Uuid(), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text(f"UPDATE brain_region_hierarchy SET species_id = :species_id WHERE id = :id"),
        {"species_id": mus_species_id, "id": aibs_brain_hierarchy_id},
    )
    op.alter_column("brain_region_hierarchy", "species_id", nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brain_region_hierarchy", sa.Column("strain_id", sa.Uuid(), nullable=True))

    op.create_index(
        op.f("ix_brain_region_hierarchy_species_id"),
        "brain_region_hierarchy",
        ["species_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_brain_region_hierarchy_strain_id"),
        "brain_region_hierarchy",
        ["strain_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_brain_region_hierarchy_species_id_species"),
        "brain_region_hierarchy",
        "species",
        ["species_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_brain_region_hierarchy_strain_id_species_id",
        "brain_region_hierarchy",
        "strain",
        ["strain_id", "species_id"],
        ["id", "species_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_brain_region_hierarchy_strain_id_species_id",
        "brain_region_hierarchy",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_brain_region_hierarchy_species_id_species"),
        "brain_region_hierarchy",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_brain_region_hierarchy_strain_id"), table_name="brain_region_hierarchy")
    op.drop_index(op.f("ix_brain_region_hierarchy_species_id"), table_name="brain_region_hierarchy")
    op.drop_column("brain_region_hierarchy", "strain_id")
    op.drop_column("brain_region_hierarchy", "species_id")
    # ### end Alembic commands ###
