"""simulation_models

Revision ID: f11898868755
Revises: e3c7dd45bc79
Create Date: 2025-06-10 21:02:56.866834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "f11898868755"
down_revision: Union[str, None] = "e3c7dd45bc79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulation", sa.Column("name", sa.String(), nullable=False))
    op.add_column("simulation", sa.Column("description", sa.String(), nullable=False))
    op.add_column(
        "simulation", sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "ix_simulation_description_vector",
        "simulation",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_simulation_name"), "simulation", ["name"], unique=False)
    public_simulation_campaign_simulation_campaign_description_vector = PGTrigger(
        schema="public",
        signature="simulation_campaign_description_vector",
        on_entity="public.simulation_campaign",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON public.simulation_campaign FOR EACH ROW EXECUTE FUNCTION tsvector_update_trigger('description_vector', 'pg_catalog.english', 'description', 'name')",
    )
    op.drop_entity(public_simulation_campaign_simulation_campaign_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_simulation_campaign_simulation_campaign_description_vector = PGTrigger(
        schema="public",
        signature="simulation_campaign_description_vector",
        on_entity="public.simulation_campaign",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON public.simulation_campaign FOR EACH ROW EXECUTE FUNCTION tsvector_update_trigger('description_vector', 'pg_catalog.english', 'description', 'name')",
    )
    op.create_entity(public_simulation_campaign_simulation_campaign_description_vector)

    op.drop_index(op.f("ix_simulation_name"), table_name="simulation")
    op.drop_index(
        "ix_simulation_description_vector", table_name="simulation", postgresql_using="gin"
    )
    op.drop_column("simulation", "description_vector")
    op.drop_column("simulation", "description")
    op.drop_column("simulation", "name")
    # ### end Alembic commands ###
