"""Default migration message

Revision ID: 634224e88212
Revises: 698536102bc8
Create Date: 2025-05-26 16:24:17.739064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "634224e88212"
down_revision: Union[str, None] = "698536102bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_pref_label", table_name="agent")
    op.create_index(op.f("ix_agent_pref_label"), "agent", ["pref_label"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_pref_label"), table_name="agent")
    op.create_index("ix_agent_pref_label", "agent", ["pref_label"], unique=True)
    # ### end Alembic commands ###
