"""empty message

Revision ID: 676937dae57e
Revises: 7ff3a7391c16
Create Date: 2025-03-13 18:42:53.245700

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "676937dae57e"
down_revision: str | None = "7ff3a7391c16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("emodel", "exemplar_morphology_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("emodel", "exemplar_morphology_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
