"""Add AnalysisNotebook entities

Revision ID: a907d441946a
Revises: e5ecb929d275
Create Date: 2025-09-26 18:04:11.678145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "a907d441946a"
down_revision: Union[str, None] = "e5ecb929d275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("subcellular", "cellular", "circuit", "system", name="analysisscale").create(
        op.get_bind()
    )
    op.create_table(
        "analysis_notebook_environment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("runtime_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_analysis_notebook_environment_id_entity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_notebook_environment")),
    )
    op.create_table(
        "analysis_notebook_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_analysis_notebook_result_id_entity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_notebook_result")),
    )
    op.create_index(
        "ix_analysis_notebook_result_description_vector",
        "analysis_notebook_result",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_analysis_notebook_result_name"), "analysis_notebook_result", ["name"], unique=False
    )
    op.create_table(
        "analysis_notebook_template",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "scale",
            postgresql.ENUM(
                "subcellular",
                "cellular",
                "circuit",
                "system",
                name="analysisscale",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("specifications", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("description_vector", postgresql.TSVECTOR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_analysis_notebook_template_id_entity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_notebook_template")),
    )
    op.create_index(
        "ix_analysis_notebook_template_description_vector",
        "analysis_notebook_template",
        ["description_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_analysis_notebook_template_name"),
        "analysis_notebook_template",
        ["name"],
        unique=False,
    )
    op.create_table(
        "analysis_notebook_execution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_notebook_template_id", sa.Uuid(), nullable=True),
        sa.Column("analysis_notebook_environment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_notebook_environment_id"],
            ["analysis_notebook_environment.id"],
            name=op.f(
                "fk_analysis_notebook_execution_analysis_notebook_environment_id_analysis_notebook_environment"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_notebook_template_id"],
            ["analysis_notebook_template.id"],
            name=op.f(
                "fk_analysis_notebook_execution_analysis_notebook_template_id_analysis_notebook_template"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["activity.id"], name=op.f("fk_analysis_notebook_execution_id_activity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_notebook_execution")),
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitytype",
        new_values=[
            "simulation_execution",
            "simulation_generation",
            "validation",
            "calibration",
            "analysis_notebook_execution",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="activity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "analysis_software_source_code",
            "brain_atlas",
            "brain_atlas_region",
            "cell_composition",
            "cell_morphology",
            "cell_morphology_protocol",
            "electrical_cell_recording",
            "electrical_recording",
            "electrical_recording_stimulus",
            "emodel",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "external_url",
            "ion_channel",
            "ion_channel_model",
            "ion_channel_recording",
            "memodel",
            "memodel_calibration_result",
            "me_type_density",
            "simulation",
            "simulation_campaign",
            "simulation_result",
            "scientific_artifact",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "subject",
            "validation_result",
            "circuit",
            "em_dense_reconstruction_dataset",
            "em_cell_mesh",
            "analysis_notebook_template",
            "analysis_notebook_environment",
            "analysis_notebook_result",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="contenttype",
        new_values=[
            "application/json",
            "application/swc",
            "application/nrrd",
            "application/obj",
            "application/hoc",
            "application/asc",
            "application/abf",
            "application/nwb",
            "application/x-hdf5",
            "text/plain",
            "application/vnd.directory",
            "application/mod",
            "application/pdf",
            "image/png",
            "image/jpeg",
            "model/gltf-binary",
            "application/gzip",
            "image/webp",
            "application/x-ipynb+json",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="content_type")
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assetlabel",
        new_values=[
            "morphology",
            "morphology_with_spines",
            "cell_composition_summary",
            "cell_composition_volumes",
            "single_neuron_synaptome_config",
            "single_neuron_synaptome_simulation_data",
            "single_neuron_simulation_data",
            "sonata_circuit",
            "compressed_sonata_circuit",
            "circuit_figures",
            "circuit_analysis_data",
            "circuit_connectivity_matrices",
            "nwb",
            "neuron_hoc",
            "emodel_optimization_output",
            "sonata_simulation_config",
            "simulation_generation_config",
            "custom_node_sets",
            "campaign_generation_config",
            "campaign_summary",
            "replay_spikes",
            "voltage_report",
            "spike_report",
            "neuron_mechanisms",
            "brain_atlas_annotation",
            "brain_atlas_region_mesh",
            "voxel_densities",
            "validation_result_figure",
            "validation_result_details",
            "simulation_designer_image",
            "circuit_visualization",
            "node_stats",
            "network_stats_a",
            "network_stats_b",
            "cell_surface_mesh",
            "jupyter_notebook",
            "requirements",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="label")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assetlabel",
        new_values=[
            "morphology",
            "morphology_with_spines",
            "cell_composition_summary",
            "cell_composition_volumes",
            "single_neuron_synaptome_config",
            "single_neuron_synaptome_simulation_data",
            "single_neuron_simulation_data",
            "sonata_circuit",
            "compressed_sonata_circuit",
            "circuit_figures",
            "circuit_analysis_data",
            "circuit_connectivity_matrices",
            "nwb",
            "neuron_hoc",
            "emodel_optimization_output",
            "sonata_simulation_config",
            "simulation_generation_config",
            "custom_node_sets",
            "campaign_generation_config",
            "campaign_summary",
            "replay_spikes",
            "voltage_report",
            "spike_report",
            "neuron_mechanisms",
            "brain_atlas_annotation",
            "brain_atlas_region_mesh",
            "voxel_densities",
            "validation_result_figure",
            "validation_result_details",
            "simulation_designer_image",
            "circuit_visualization",
            "node_stats",
            "network_stats_a",
            "network_stats_b",
            "cell_surface_mesh",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="label")
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="contenttype",
        new_values=[
            "application/json",
            "application/swc",
            "application/nrrd",
            "application/obj",
            "application/hoc",
            "application/asc",
            "application/abf",
            "application/nwb",
            "application/x-hdf5",
            "text/plain",
            "application/vnd.directory",
            "application/mod",
            "application/pdf",
            "image/png",
            "image/jpeg",
            "model/gltf-binary",
            "application/gzip",
            "image/webp",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="content_type")
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="entitytype",
        new_values=[
            "analysis_software_source_code",
            "brain_atlas",
            "brain_atlas_region",
            "cell_composition",
            "cell_morphology",
            "cell_morphology_protocol",
            "electrical_cell_recording",
            "electrical_recording",
            "electrical_recording_stimulus",
            "emodel",
            "experimental_bouton_density",
            "experimental_neuron_density",
            "experimental_synapses_per_connection",
            "external_url",
            "ion_channel",
            "ion_channel_model",
            "ion_channel_recording",
            "memodel",
            "memodel_calibration_result",
            "me_type_density",
            "simulation",
            "simulation_campaign",
            "simulation_result",
            "scientific_artifact",
            "single_neuron_simulation",
            "single_neuron_synaptome",
            "single_neuron_synaptome_simulation",
            "subject",
            "validation_result",
            "circuit",
            "em_dense_reconstruction_dataset",
            "em_cell_mesh",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="entity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitytype",
        new_values=["simulation_execution", "simulation_generation", "validation", "calibration"],
        affected_columns=[
            TableReference(table_schema="public", table_name="activity", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_table("analysis_notebook_execution")
    op.drop_index(
        op.f("ix_analysis_notebook_template_name"), table_name="analysis_notebook_template"
    )
    op.drop_index(
        "ix_analysis_notebook_template_description_vector",
        table_name="analysis_notebook_template",
        postgresql_using="gin",
    )
    op.drop_table("analysis_notebook_template")
    op.drop_index(op.f("ix_analysis_notebook_result_name"), table_name="analysis_notebook_result")
    op.drop_index(
        "ix_analysis_notebook_result_description_vector",
        table_name="analysis_notebook_result",
        postgresql_using="gin",
    )
    op.drop_table("analysis_notebook_result")
    op.drop_table("analysis_notebook_environment")
    sa.Enum("subcellular", "cellular", "circuit", "system", name="analysisscale").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
