"""Default migration message

Revision ID: fb22746e4889
Revises: afdb7e24034c
Create Date: 2025-07-17 11:45:28.891152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "fb22746e4889"
down_revision: Union[str, None] = "afdb7e24034c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_mtype_per_entity", "mtype_classification", ["entity_id", "mtype_class_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_mtype_per_entity", "mtype_classification", type_="unique")
    # ### end Alembic commands ###
