"""Default migration message

Revision ID: 5c06fae70203
Revises: 0302e30b2a91
Create Date: 2025-04-10 20:44:04.636212

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c06fae70203"
down_revision: str | None = "0302e30b2a91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "measurement_record",
        "unit",
        existing_type=postgresql.ENUM(
            "dimensionless", "linear_density", "volume_density", name="measurementunit"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    sa.Enum("dimensionless", "linear_density", "volume_density", name="measurementunit").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("dimensionless", "linear_density", "volume_density", name="measurementunit").create(
        op.get_bind()
    )
    op.alter_column(
        "measurement_record",
        "unit",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "dimensionless", "linear_density", "volume_density", name="measurementunit"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
