"""Add measurement_label

Revision ID: 3f43728354a6
Revises: fa068879e345
Create Date: 2025-12-22 17:36:16.051100

"""

import hashlib
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "3f43728354a6"
down_revision: Union[str, None] = "fa068879e345"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ADMIN_ID = "cd613e30-d8f1-4adf-91b7-584a2265b1f5"  # Admin/OBI


def _make_uuid(s: str) -> uuid.UUID:
    """Make a new deterministic uuid from a given string.

    Not to be used when properly random uuids are needed!
    """
    h = hashlib.sha256(s.encode("utf-8")).digest()[:16]
    return uuid.UUID(bytes=h, version=4)


def _migrate_data() -> None:
    conn = op.get_bind()

    # All the existing labels belong to cell_morphology
    entity_type = "cell_morphology"

    # Get distinct pref_labels and generate deterministic UUIDs
    result = conn.execute(
        sa.text("""
            SELECT DISTINCT pref_label
            FROM measurement_kind
            ORDER BY pref_label
        """)
    )
    data = [
        {
            "id": _make_uuid(f"{entity_type}:{row[0]}"),
            "pref_label": row[0],
            "entity_type": entity_type,
            "created_by_id": ADMIN_ID,
            "updated_by_id": ADMIN_ID,
        }
        for row in result
    ]

    # Populate measurement_label
    if data:
        measurement_label = sa.table(
            "measurement_label",
            sa.column("id", sa.Uuid()),
            sa.column("pref_label", sa.String()),
            sa.column("entity_type"),
            sa.column("created_by_id", sa.Uuid()),
            sa.column("updated_by_id", sa.Uuid()),
        )
        op.bulk_insert(measurement_label, data)

    # Update measurement_kind.measurement_label_id
    conn.execute(
        sa.text(f"""
            UPDATE measurement_kind
            SET measurement_label_id = ml.id
            FROM measurement_label ml
            WHERE ml.entity_type = '{entity_type}'::entitytype
            AND ml.pref_label = measurement_kind.pref_label
        """)
    )


def _restore_data() -> None:
    conn = op.get_bind()

    # Restore pref_label from measurement_label
    conn = op.get_bind()
    conn.execute(
        sa.text("""
            UPDATE measurement_kind
            SET pref_label = ml.pref_label
            FROM measurement_label ml
            WHERE ml.id = measurement_kind.measurement_label_id
        """)
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurement_label",
        sa.Column(
            "entity_type",
            postgresql.ENUM(
                "analysis_software_source_code",
                "brain_atlas",
                "brain_atlas_region",
                "cell_composition",
                "cell_morphology",
                "cell_morphology_protocol",
                "electrical_cell_recording",
                "electrical_recording",
                "electrical_recording_stimulus",
                "emodel",
                "experimental_bouton_density",
                "experimental_neuron_density",
                "experimental_synapses_per_connection",
                "external_url",
                "ion_channel_model",
                "ion_channel_modeling_campaign",
                "ion_channel_modeling_config",
                "ion_channel_recording",
                "memodel",
                "memodel_calibration_result",
                "me_type_density",
                "simulation",
                "simulation_campaign",
                "simulation_result",
                "scientific_artifact",
                "single_neuron_simulation",
                "single_neuron_synaptome",
                "single_neuron_synaptome_simulation",
                "subject",
                "validation_result",
                "circuit",
                "circuit_extraction_campaign",
                "circuit_extraction_config",
                "em_dense_reconstruction_dataset",
                "em_cell_mesh",
                "analysis_notebook_template",
                "analysis_notebook_environment",
                "analysis_notebook_result",
                "skeletonization_config",
                "skeletonization_campaign",
                name="entitytype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("pref_label", sa.String(), nullable=False),
        sa.Column("definition", sa.String(), server_default="", nullable=False),
        sa.Column("alt_label", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["agent.id"], name=op.f("fk_measurement_label_created_by_id_agent")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["agent.id"], name=op.f("fk_measurement_label_updated_by_id_agent")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurement_label")),
    )
    op.create_index(
        op.f("ix_measurement_label_created_by_id"),
        "measurement_label",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurement_label_creation_date"),
        "measurement_label",
        ["creation_date"],
        unique=False,
    )
    op.create_index(
        "ix_measurement_label_entity_type_pref_label",
        "measurement_label",
        ["entity_type", "pref_label"],
        unique=True,
    )
    op.create_index(
        op.f("ix_measurement_label_pref_label"), "measurement_label", ["pref_label"], unique=False
    )
    op.create_index(
        op.f("ix_measurement_label_updated_by_id"),
        "measurement_label",
        ["updated_by_id"],
        unique=False,
    )

    # Add measurement_label_id as nullable
    op.add_column("measurement_kind", sa.Column("measurement_label_id", sa.Uuid(), nullable=True))

    _migrate_data()

    # Convert measurement_label_id to not nullable
    op.alter_column("measurement_kind", "measurement_label_id", nullable=False)

    op.drop_index(op.f("ix_measurement_kind_pref_label"), table_name="measurement_kind")
    op.drop_constraint(
        op.f("uq_measurement_kind_measurement_annotation_id"), "measurement_kind", type_="unique"
    )
    op.create_unique_constraint(
        "uq_measurement_kind_measurement_annotation_id",
        "measurement_kind",
        ["measurement_annotation_id", "measurement_label_id", "structural_domain"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_measurement_kind_measurement_label_id"),
        "measurement_kind",
        ["measurement_label_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_measurement_kind_measurement_label_id_measurement_label"),
        "measurement_kind",
        "measurement_label",
        ["measurement_label_id"],
        ["id"],
    )
    op.drop_column("measurement_kind", "pref_label")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="measurementunit",
        new_values=[
            "dimensionless",
            "linear_density__1_um",
            "area_density__1_um2",
            "volume_density__1_mm3",
            "linear__um",
            "area__um2",
            "volume__um3",
            "volume__mm3",
            "angle__radian",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="measurement_item", column_name="unit"
            ),
            TableReference(
                table_schema="public", table_name="measurement_record", column_name="unit"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="measurementunit",
        new_values=[
            "dimensionless",
            "linear_density__1_um",
            "volume_density__1_mm3",
            "linear__um",
            "area__um2",
            "volume__mm3",
            "angle__radian",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="measurement_item", column_name="unit"
            ),
            TableReference(
                table_schema="public", table_name="measurement_record", column_name="unit"
            ),
        ],
        enum_values_to_rename=[],
    )

    # Add pref_label as nullable
    op.add_column(
        "measurement_kind",
        sa.Column("pref_label", sa.VARCHAR(), autoincrement=False, nullable=True),
    )

    _restore_data()

    # Convert pref_label to not nullable
    op.alter_column("measurement_kind", "pref_label", nullable=False)

    op.drop_constraint(
        op.f("fk_measurement_kind_measurement_label_id_measurement_label"),
        "measurement_kind",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_measurement_kind_measurement_label_id"), table_name="measurement_kind")
    op.drop_constraint(
        "uq_measurement_kind_measurement_annotation_id", "measurement_kind", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_measurement_kind_measurement_annotation_id"),
        "measurement_kind",
        ["measurement_annotation_id", "pref_label", "structural_domain"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_measurement_kind_pref_label"), "measurement_kind", ["pref_label"], unique=False
    )
    op.drop_column("measurement_kind", "measurement_label_id")
    op.drop_index(op.f("ix_measurement_label_updated_by_id"), table_name="measurement_label")
    op.drop_index(op.f("ix_measurement_label_pref_label"), table_name="measurement_label")
    op.drop_index("ix_measurement_label_entity_type_pref_label", table_name="measurement_label")
    op.drop_index(op.f("ix_measurement_label_creation_date"), table_name="measurement_label")
    op.drop_index(op.f("ix_measurement_label_created_by_id"), table_name="measurement_label")
    op.drop_table("measurement_label")
    # ### end Alembic commands ###
