"""Default migration message

Revision ID: 551b34524731
Revises: 34a3ede07dff
Create Date: 2025-04-15 15:24:20.192571

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "551b34524731"
down_revision: str | None = "34a3ede07dff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_age", "age", ["id", "value", "min_value", "max_value", "unit", "period"]
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="electricalrecordingstimulusshape",
        new_values=[
            "cheops",
            "constant",
            "pulse",
            "step",
            "ramp",
            "noise",
            "sinusoidal",
            "other",
            "two_steps",
            "unknown",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="electrical_recording_stimulus",
                column_name="shape",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="electricalrecordingstimulusshape",
        new_values=["step", "ramp", "noise", "sinusoidal", "other", "unknown"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="electrical_recording_stimulus",
                column_name="shape",
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_constraint("uq_age", "age", type_="unique")
    # ### end Alembic commands ###
