"""Default migration message

Revision ID: 102873c17da5
Revises: 65a70a536013
Create Date: 2025-04-08 18:24:03.877516

"""

from collections.abc import Sequence

from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "102873c17da5"
down_revision: str | None = "65a70a536013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_experimental_neuron_density_experimental_neuron_density_description_vector = PGTrigger(
        schema="public",
        signature="experimental_neuron_density_description_vector",
        on_entity="public.experimental_neuron_density",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON experimental_neuron_density\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(
        public_experimental_neuron_density_experimental_neuron_density_description_vector
    )

    public_experimental_synapses_per_connection_experimental_synapses_per_connection_description_vector = PGTrigger(
        schema="public",
        signature="experimental_synapses_per_connection_description_vector",
        on_entity="public.experimental_synapses_per_connection",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON experimental_synapses_per_connection\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(
        public_experimental_synapses_per_connection_experimental_synapses_per_connection_description_vector
    )

    public_experimental_bouton_density_experimental_bouton_density_description_vector = PGTrigger(
        schema="public",
        signature="experimental_bouton_density_description_vector",
        on_entity="public.experimental_bouton_density",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON experimental_bouton_density\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(
        public_experimental_bouton_density_experimental_bouton_density_description_vector
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_experimental_bouton_density_experimental_bouton_density_description_vector = PGTrigger(
        schema="public",
        signature="experimental_bouton_density_description_vector",
        on_entity="public.experimental_bouton_density",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON experimental_bouton_density\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(
        public_experimental_bouton_density_experimental_bouton_density_description_vector
    )

    public_experimental_synapses_per_connection_experimental_synapses_per_connection_description_vector = PGTrigger(
        schema="public",
        signature="experimental_synapses_per_connection_description_vector",
        on_entity="public.experimental_synapses_per_connection",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON experimental_synapses_per_connection\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(
        public_experimental_synapses_per_connection_experimental_synapses_per_connection_description_vector
    )

    public_experimental_neuron_density_experimental_neuron_density_description_vector = PGTrigger(
        schema="public",
        signature="experimental_neuron_density_description_vector",
        on_entity="public.experimental_neuron_density",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON experimental_neuron_density\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(
        public_experimental_neuron_density_experimental_neuron_density_description_vector
    )

    # ### end Alembic commands ###
