"""Default migration message

Revision ID: 77be41ab7be8
Revises: b4580e028c70
Create Date: 2025-03-31 20:33:47.568153

"""

from collections.abc import Sequence

from alembic_utils.pg_trigger import PGTrigger

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77be41ab7be8"
down_revision: str | None = "b4580e028c70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_electrical_cell_recording_electrical_cell_recording_description_vector = PGTrigger(
        schema="public",
        signature="electrical_cell_recording_description_vector",
        on_entity="public.electrical_cell_recording",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON electrical_cell_recording\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_electrical_cell_recording_electrical_cell_recording_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_electrical_cell_recording_electrical_cell_recording_description_vector = PGTrigger(
        schema="public",
        signature="electrical_cell_recording_description_vector",
        on_entity="public.electrical_cell_recording",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON electrical_cell_recording\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_electrical_cell_recording_electrical_cell_recording_description_vector)

    # ### end Alembic commands ###
