"""deletion_cascades

Revision ID: 0e71c9bda768
Revises: a5789f03b002
Create Date: 2025-12-14 00:48:19.180598

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "0e71c9bda768"
down_revision: Union[str, None] = "a5789f03b002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_annotation_entity_id_entity"), "annotation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_annotation_entity_id_entity"),
        "annotation",
        "entity",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_asset_entity_id_entity"), "asset", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_asset_entity_id_entity"),
        "asset",
        "entity",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_contribution_entity_id_entity"), "contribution", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_contribution_entity_id_entity"),
        "contribution",
        "entity",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_etype_classification_entity_id_entity"), "etype_classification", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_etype_classification_entity_id_entity"),
        "etype_classification",
        "entity",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_generation_generation_entity_id_entity"), "generation", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_generation_generation_entity_id_entity"),
        "generation",
        "entity",
        ["generation_entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_measurement_annotation_entity_id_entity"),
        "measurement_annotation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_measurement_annotation_entity_id_entity"),
        "measurement_annotation",
        "entity",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_mtype_classification_entity_id_entity"), "mtype_classification", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_mtype_classification_entity_id_entity"),
        "mtype_classification",
        "entity",
        ["entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_external_url_link_scientific_art_9473"),
        "scientific_artifact_external_url_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_external_url_link_scientific_artifact_id_scientific_artifact"),
        "scientific_artifact_external_url_link",
        "scientific_artifact",
        ["scientific_artifact_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_publication_link_scientific_arti_91de"),
        "scientific_artifact_publication_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_publication_link_scientific_artifact_id_scientific_artifact"),
        "scientific_artifact_publication_link",
        "scientific_artifact",
        ["scientific_artifact_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_usage_usage_entity_id_entity"), "usage", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_usage_usage_entity_id_entity"), "usage", "entity", ["usage_entity_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_usage_usage_entity_id_entity"), "usage", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_usage_usage_entity_id_entity"),
        "usage",
        "entity",
        ["usage_entity_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_publication_link_scientific_artifact_id_scientific_artifact"),
        "scientific_artifact_publication_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_publication_link_scientific_arti_91de"),
        "scientific_artifact_publication_link",
        "scientific_artifact",
        ["scientific_artifact_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_external_url_link_scientific_artifact_id_scientific_artifact"),
        "scientific_artifact_external_url_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_external_url_link_scientific_art_9473"),
        "scientific_artifact_external_url_link",
        "scientific_artifact",
        ["scientific_artifact_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_mtype_classification_entity_id_entity"), "mtype_classification", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_mtype_classification_entity_id_entity"),
        "mtype_classification",
        "entity",
        ["entity_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_measurement_annotation_entity_id_entity"),
        "measurement_annotation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_measurement_annotation_entity_id_entity"),
        "measurement_annotation",
        "entity",
        ["entity_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_generation_generation_entity_id_entity"), "generation", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_generation_generation_entity_id_entity"),
        "generation",
        "entity",
        ["generation_entity_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_etype_classification_entity_id_entity"), "etype_classification", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_etype_classification_entity_id_entity"),
        "etype_classification",
        "entity",
        ["entity_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_contribution_entity_id_entity"), "contribution", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_contribution_entity_id_entity"), "contribution", "entity", ["entity_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_asset_entity_id_entity"), "asset", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_asset_entity_id_entity"), "asset", "entity", ["entity_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_annotation_entity_id_entity"), "annotation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_annotation_entity_id_entity"), "annotation", "entity", ["entity_id"], ["id"]
    )
    # ### end Alembic commands ###
