"""Default migration message

Revision ID: f2a2c11cb9f3
Revises: c704517dd6a2
Create Date: 2025-06-24 21:01:09.230707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "f2a2c11cb9f3"
down_revision: Union[str, None] = "c704517dd6a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="contenttype",
        new_values=[
            "application/json",
            "application/swc",
            "application/nrrd",
            "application/obj",
            "application/hoc",
            "application/asc",
            "application/abf",
            "application/nwb",
            "application/x-hdf5",
            "text/plain",
            "application/vnd.directory",
            "application/mod",
            "application/pdf",
            "image/png",
            "image/jpeg",
            "application/octet-stream",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="content_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="contenttype",
        new_values=[
            "application/json",
            "application/swc",
            "application/nrrd",
            "application/obj",
            "application/hoc",
            "application/asc",
            "application/abf",
            "application/nwb",
            "application/x-hdf5",
            "text/plain",
            "application/vnd.directory",
            "application/mod",
            "application/pdf",
            "image/png",
            "image/jpeg",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="content_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
