"""Add triggers for EMDenseReconstructionDataset

Revision ID: fe5a04a4acab
Revises: 9ff8cac89315
Create Date: 2025-08-25 15:52:12.434935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "fe5a04a4acab"
down_revision: Union[str, None] = "9ff8cac89315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_em_dense_reconstruction_dataset_em_dense_reconstruction_dataset_description_vector = PGTrigger(
        schema="public",
        signature="em_dense_reconstruction_dataset_description_vector",
        on_entity="public.em_dense_reconstruction_dataset",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON em_dense_reconstruction_dataset\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(
        public_em_dense_reconstruction_dataset_em_dense_reconstruction_dataset_description_vector
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_em_dense_reconstruction_dataset_em_dense_reconstruction_dataset_description_vector = PGTrigger(
        schema="public",
        signature="em_dense_reconstruction_dataset_description_vector",
        on_entity="public.em_dense_reconstruction_dataset",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON em_dense_reconstruction_dataset\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(
        public_em_dense_reconstruction_dataset_em_dense_reconstruction_dataset_description_vector
    )

    # ### end Alembic commands ###
