"""empty message

Revision ID: 1de0e9a0a8e1
Revises: b300b17671e3
Create Date: 2025-02-14 12:58:05.815545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1de0e9a0a8e1"
down_revision: str | None = "b300b17671e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("CREATED", "DELETED", name="assetstatus").create(op.get_bind())
    op.create_table(
        "asset",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("CREATED", "DELETED", name="assetstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("fullpath", sa.String(), nullable=False),
        sa.Column("bucket_name", sa.String(), nullable=False),
        sa.Column("is_directory", sa.Boolean(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity.id"], name=op.f("fk_asset_entity_id_entity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
    )
    op.create_index(op.f("ix_asset_creation_date"), "asset", ["creation_date"], unique=False)
    op.create_index(op.f("ix_asset_entity_id"), "asset", ["entity_id"], unique=False)
    op.create_index(
        "ix_asset_fullpath",
        "asset",
        ["fullpath"],
        unique=True,
        postgresql_where=sa.text("status != 'DELETED'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_asset_fullpath", table_name="asset", postgresql_where=sa.text("status != 'DELETED'")
    )
    op.drop_index(op.f("ix_asset_entity_id"), table_name="asset")
    op.drop_index(op.f("ix_asset_creation_date"), table_name="asset")
    op.drop_table("asset")
    sa.Enum("CREATED", "DELETED", name="assetstatus").drop(op.get_bind())
    # ### end Alembic commands ###
