"""Default migration message

Revision ID: 653df0eee898
Revises: 698536102bc8
Create Date: 2025-05-26 14:25:04.120757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "653df0eee898"
down_revision: Union[str, None] = "698536102bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "derivation",
        sa.Column("used_id", sa.Uuid(), nullable=False),
        sa.Column("generated_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_id"], ["entity.id"], name=op.f("fk_derivation_generated_id_entity")
        ),
        sa.ForeignKeyConstraint(
            ["used_id"], ["entity.id"], name=op.f("fk_derivation_used_id_entity")
        ),
        sa.PrimaryKeyConstraint("used_id", "generated_id", name=op.f("pk_derivation")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("derivation")
    # ### end Alembic commands ###
