"""Currents

Revision ID: a58ae4b9c274
Revises: 077b4ad24943
Create Date: 2025-05-10 11:00:34.458878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "a58ae4b9c274"
down_revision: Union[str, None] = "077b4ad24943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memodel", sa.Column("holding_current", sa.Float(), nullable=False))
    op.add_column("memodel", sa.Column("threshold_current", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memodel", "threshold_current")
    op.drop_column("memodel", "holding_current")
    # ### end Alembic commands ###
