"""Default migration message

Revision ID: 84c6a3624b63
Revises: a6f5259d5604
Create Date: 2025-06-05 16:22:46.505656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "84c6a3624b63"
down_revision: Union[str, None] = "a6f5259d5604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_simulation_campaign_simulation_campaign_description_vector = PGTrigger(
        schema="public",
        signature="simulation_campaign_description_vector",
        on_entity="public.simulation_campaign",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON simulation_campaign\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_simulation_campaign_simulation_campaign_description_vector)

    public_circuit_circuit_description_vector = PGTrigger(
        schema="public",
        signature="circuit_description_vector",
        on_entity="public.circuit",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON circuit\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_circuit_circuit_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_circuit_circuit_description_vector = PGTrigger(
        schema="public",
        signature="circuit_description_vector",
        on_entity="public.circuit",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON circuit\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_circuit_circuit_description_vector)

    public_simulation_campaign_simulation_campaign_description_vector = PGTrigger(
        schema="public",
        signature="simulation_campaign_description_vector",
        on_entity="public.simulation_campaign",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON simulation_campaign\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_simulation_campaign_simulation_campaign_description_vector)

    # ### end Alembic commands ###
