"""target_simulator

Revision ID: cdab088f422f
Revises: 5b313e362c15
Create Date: 2026-04-23 13:53:22.699519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "cdab088f422f"
down_revision: Union[str, None] = "5b313e362c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="targetsimulator",
        new_values=["NEURON", "CORENEURON", "LearningEngine", "Brian2"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="circuit",
                column_name="target_simulator",
                existing_server_default="'NEURON'::targetsimulator",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="targetsimulator",
        new_values=["NEURON", "CORENEURON", "LearningEngine", "brian2"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="circuit",
                column_name="target_simulator",
                existing_server_default="'NEURON'::targetsimulator",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
