"""Split User from Person

Revision ID: 122ee418a384
Revises: 79dbeada57f3
Create Date: 2026-07-28 17:17:10.942746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "122ee418a384"
down_revision: Union[str, None] = "79dbeada57f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("given_name", sa.String(), nullable=True),
        sa.Column("family_name", sa.String(), nullable=True),
        sa.Column("pref_label", sa.String(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_creation_date"), "user", ["creation_date"], unique=False)
    op.create_index(op.f("ix_user_pref_label"), "user", ["pref_label"], unique=False)
    # Populate user table from person rows that have a sub_id (all platform users)
    op.execute("""
        INSERT INTO "user" (id, given_name, family_name, pref_label, creation_date, update_date)
        SELECT p.sub_id, p.given_name, p.family_name, a.pref_label, a.creation_date, a.update_date
        FROM person p
        JOIN agent a ON a.id = p.id
        WHERE p.sub_id IS NOT NULL
    """)
    # Remap created_by_id / updated_by_id on all base tables from agent.id to person.sub_id
    for table in [
        "activity",
        "agent",
        "annotation",
        "annotation_body",
        "asset",
        "brain_region",
        "brain_region_hierarchy",
        "contribution",
        "derivation",
        "entity",
        "etype_class",
        "etype_classification",
        "external_url",
        "ion",
        "ion_channel",
        "license",
        "measurement_annotation",
        "measurement_label",
        "mtype_class",
        "mtype_classification",
        "publication",
        "role",
        "scientific_artifact_external_url_link",
        "scientific_artifact_publication_link",
        "species",
        "strain",
    ]:
        op.execute(f"""
            UPDATE "{table}" t
            SET created_by_id = p_c.sub_id,
                updated_by_id = p_u.sub_id
            FROM person p_c, person p_u
            WHERE p_c.id = t.created_by_id
              AND p_u.id = t.updated_by_id
        """)
    op.drop_constraint(op.f("fk_activity_created_by_id_agent"), "activity", type_="foreignkey")
    op.drop_constraint(op.f("fk_activity_updated_by_id_agent"), "activity", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_activity_created_by_id_user"), "activity", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_activity_updated_by_id_user"), "activity", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_agent_updated_by_id_agent"), "agent", type_="foreignkey")
    op.drop_constraint(op.f("fk_agent_created_by_id_agent"), "agent", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_agent_created_by_id_user"), "agent", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_agent_updated_by_id_user"), "agent", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_annotation_updated_by_id_agent"), "annotation", type_="foreignkey")
    op.drop_constraint(op.f("fk_annotation_created_by_id_agent"), "annotation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_annotation_updated_by_id_user"), "annotation", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_annotation_created_by_id_user"), "annotation", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_annotation_body_updated_by_id_agent"), "annotation_body", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_annotation_body_created_by_id_agent"), "annotation_body", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_annotation_body_created_by_id_user"),
        "annotation_body",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_annotation_body_updated_by_id_user"),
        "annotation_body",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_asset_created_by_id_agent"), "asset", type_="foreignkey")
    op.drop_constraint(op.f("fk_asset_updated_by_id_agent"), "asset", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_asset_created_by_id_user"), "asset", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_asset_updated_by_id_user"), "asset", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_brain_region_updated_by_id_agent"), "brain_region", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_brain_region_created_by_id_agent"), "brain_region", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_brain_region_created_by_id_user"),
        "brain_region",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_brain_region_updated_by_id_user"),
        "brain_region",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_brain_region_hierarchy_created_by_id_agent"),
        "brain_region_hierarchy",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_brain_region_hierarchy_updated_by_id_agent"),
        "brain_region_hierarchy",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_brain_region_hierarchy_updated_by_id_user"),
        "brain_region_hierarchy",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_brain_region_hierarchy_created_by_id_user"),
        "brain_region_hierarchy",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_contribution_created_by_id_agent"), "contribution", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_contribution_updated_by_id_agent"), "contribution", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_contribution_created_by_id_user"),
        "contribution",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_contribution_updated_by_id_user"),
        "contribution",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_derivation_updated_by_id_agent"), "derivation", type_="foreignkey")
    op.drop_constraint(op.f("fk_derivation_created_by_id_agent"), "derivation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_derivation_updated_by_id_user"), "derivation", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_derivation_created_by_id_user"), "derivation", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_entity_created_by_id_agent"), "entity", type_="foreignkey")
    op.drop_constraint(op.f("fk_entity_updated_by_id_agent"), "entity", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_entity_updated_by_id_user"), "entity", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_entity_created_by_id_user"), "entity", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_etype_class_created_by_id_agent"), "etype_class", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_etype_class_updated_by_id_agent"), "etype_class", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_etype_class_updated_by_id_user"), "etype_class", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_etype_class_created_by_id_user"), "etype_class", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_etype_classification_updated_by_id_agent"),
        "etype_classification",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_etype_classification_created_by_id_agent"),
        "etype_classification",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_etype_classification_updated_by_id_user"),
        "etype_classification",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_etype_classification_created_by_id_user"),
        "etype_classification",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_external_url_updated_by_id_agent"), "external_url", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_external_url_created_by_id_agent"), "external_url", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_external_url_updated_by_id_user"),
        "external_url",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_external_url_created_by_id_user"),
        "external_url",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_ion_updated_by_id_agent"), "ion", type_="foreignkey")
    op.drop_constraint(op.f("fk_ion_created_by_id_agent"), "ion", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_ion_created_by_id_user"), "ion", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_ion_updated_by_id_user"), "ion", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_ion_channel_updated_by_id_agent"), "ion_channel", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_ion_channel_created_by_id_agent"), "ion_channel", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_ion_channel_created_by_id_user"), "ion_channel", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_ion_channel_updated_by_id_user"), "ion_channel", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_license_created_by_id_agent"), "license", type_="foreignkey")
    op.drop_constraint(op.f("fk_license_updated_by_id_agent"), "license", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_license_created_by_id_user"), "license", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_license_updated_by_id_user"), "license", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_measurement_annotation_updated_by_id_agent"),
        "measurement_annotation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_measurement_annotation_created_by_id_agent"),
        "measurement_annotation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_measurement_annotation_updated_by_id_user"),
        "measurement_annotation",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_measurement_annotation_created_by_id_user"),
        "measurement_annotation",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_measurement_label_created_by_id_agent"), "measurement_label", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_measurement_label_updated_by_id_agent"), "measurement_label", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_measurement_label_created_by_id_user"),
        "measurement_label",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_measurement_label_updated_by_id_user"),
        "measurement_label",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_mtype_class_updated_by_id_agent"), "mtype_class", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_mtype_class_created_by_id_agent"), "mtype_class", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_mtype_class_created_by_id_user"), "mtype_class", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_mtype_class_updated_by_id_user"), "mtype_class", "user", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_mtype_classification_updated_by_id_agent"),
        "mtype_classification",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_mtype_classification_created_by_id_agent"),
        "mtype_classification",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_mtype_classification_updated_by_id_user"),
        "mtype_classification",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_mtype_classification_created_by_id_user"),
        "mtype_classification",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_person_sub_id"), table_name="person")
    op.drop_column("person", "sub_id")
    op.drop_constraint(
        op.f("fk_publication_updated_by_id_agent"), "publication", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_publication_created_by_id_agent"), "publication", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_publication_updated_by_id_user"), "publication", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_publication_created_by_id_user"), "publication", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_role_created_by_id_agent"), "role", type_="foreignkey")
    op.drop_constraint(op.f("fk_role_updated_by_id_agent"), "role", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_updated_by_id_user"), "role", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_role_created_by_id_user"), "role", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_external_url_link_created_by_id_agent"),
        "scientific_artifact_external_url_link",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_external_url_link_updated_by_id_agent"),
        "scientific_artifact_external_url_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_external_url_link_created_by_id_user"),
        "scientific_artifact_external_url_link",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_external_url_link_updated_by_id_user"),
        "scientific_artifact_external_url_link",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_publication_link_created_by_id_agent"),
        "scientific_artifact_publication_link",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_publication_link_updated_by_id_agent"),
        "scientific_artifact_publication_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_publication_link_created_by_id_user"),
        "scientific_artifact_publication_link",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_publication_link_updated_by_id_user"),
        "scientific_artifact_publication_link",
        "user",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_species_updated_by_id_agent"), "species", type_="foreignkey")
    op.drop_constraint(op.f("fk_species_created_by_id_agent"), "species", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_species_updated_by_id_user"), "species", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_species_created_by_id_user"), "species", "user", ["created_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_strain_updated_by_id_agent"), "strain", type_="foreignkey")
    op.drop_constraint(op.f("fk_strain_created_by_id_agent"), "strain", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_strain_updated_by_id_user"), "strain", "user", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_strain_created_by_id_user"), "strain", "user", ["created_by_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_strain_created_by_id_user"), "strain", type_="foreignkey")
    op.drop_constraint(op.f("fk_strain_updated_by_id_user"), "strain", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_strain_created_by_id_agent"), "strain", "agent", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_strain_updated_by_id_agent"), "strain", "agent", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_species_created_by_id_user"), "species", type_="foreignkey")
    op.drop_constraint(op.f("fk_species_updated_by_id_user"), "species", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_species_created_by_id_agent"), "species", "agent", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_species_updated_by_id_agent"), "species", "agent", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_publication_link_updated_by_id_user"),
        "scientific_artifact_publication_link",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_publication_link_created_by_id_user"),
        "scientific_artifact_publication_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_publication_link_updated_by_id_agent"),
        "scientific_artifact_publication_link",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_publication_link_created_by_id_agent"),
        "scientific_artifact_publication_link",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_external_url_link_updated_by_id_user"),
        "scientific_artifact_external_url_link",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_scientific_artifact_external_url_link_created_by_id_user"),
        "scientific_artifact_external_url_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_external_url_link_updated_by_id_agent"),
        "scientific_artifact_external_url_link",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_scientific_artifact_external_url_link_created_by_id_agent"),
        "scientific_artifact_external_url_link",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_role_created_by_id_user"), "role", type_="foreignkey")
    op.drop_constraint(op.f("fk_role_updated_by_id_user"), "role", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_updated_by_id_agent"), "role", "agent", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_role_created_by_id_agent"), "role", "agent", ["created_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_publication_created_by_id_user"), "publication", type_="foreignkey")
    op.drop_constraint(op.f("fk_publication_updated_by_id_user"), "publication", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_publication_created_by_id_agent"),
        "publication",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_publication_updated_by_id_agent"),
        "publication",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.add_column("person", sa.Column("sub_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f("ix_person_sub_id"), "person", ["sub_id"], unique=True)
    op.drop_constraint(
        op.f("fk_mtype_classification_created_by_id_user"),
        "mtype_classification",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_mtype_classification_updated_by_id_user"),
        "mtype_classification",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_mtype_classification_created_by_id_agent"),
        "mtype_classification",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_mtype_classification_updated_by_id_agent"),
        "mtype_classification",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_mtype_class_updated_by_id_user"), "mtype_class", type_="foreignkey")
    op.drop_constraint(op.f("fk_mtype_class_created_by_id_user"), "mtype_class", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_mtype_class_created_by_id_agent"),
        "mtype_class",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_mtype_class_updated_by_id_agent"),
        "mtype_class",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_measurement_label_updated_by_id_user"), "measurement_label", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_measurement_label_created_by_id_user"), "measurement_label", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_measurement_label_updated_by_id_agent"),
        "measurement_label",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_measurement_label_created_by_id_agent"),
        "measurement_label",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_measurement_annotation_created_by_id_user"),
        "measurement_annotation",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_measurement_annotation_updated_by_id_user"),
        "measurement_annotation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_measurement_annotation_created_by_id_agent"),
        "measurement_annotation",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_measurement_annotation_updated_by_id_agent"),
        "measurement_annotation",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_license_updated_by_id_user"), "license", type_="foreignkey")
    op.drop_constraint(op.f("fk_license_created_by_id_user"), "license", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_license_updated_by_id_agent"), "license", "agent", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_license_created_by_id_agent"), "license", "agent", ["created_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_ion_channel_updated_by_id_user"), "ion_channel", type_="foreignkey")
    op.drop_constraint(op.f("fk_ion_channel_created_by_id_user"), "ion_channel", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_ion_channel_created_by_id_agent"),
        "ion_channel",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_ion_channel_updated_by_id_agent"),
        "ion_channel",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_ion_updated_by_id_user"), "ion", type_="foreignkey")
    op.drop_constraint(op.f("fk_ion_created_by_id_user"), "ion", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_ion_created_by_id_agent"), "ion", "agent", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_ion_updated_by_id_agent"), "ion", "agent", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_external_url_created_by_id_user"), "external_url", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_external_url_updated_by_id_user"), "external_url", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_external_url_created_by_id_agent"),
        "external_url",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_external_url_updated_by_id_agent"),
        "external_url",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_etype_classification_created_by_id_user"),
        "etype_classification",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_etype_classification_updated_by_id_user"),
        "etype_classification",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_etype_classification_created_by_id_agent"),
        "etype_classification",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_etype_classification_updated_by_id_agent"),
        "etype_classification",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_etype_class_created_by_id_user"), "etype_class", type_="foreignkey")
    op.drop_constraint(op.f("fk_etype_class_updated_by_id_user"), "etype_class", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_etype_class_updated_by_id_agent"),
        "etype_class",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_etype_class_created_by_id_agent"),
        "etype_class",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_entity_created_by_id_user"), "entity", type_="foreignkey")
    op.drop_constraint(op.f("fk_entity_updated_by_id_user"), "entity", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_entity_updated_by_id_agent"), "entity", "agent", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_entity_created_by_id_agent"), "entity", "agent", ["created_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_derivation_created_by_id_user"), "derivation", type_="foreignkey")
    op.drop_constraint(op.f("fk_derivation_updated_by_id_user"), "derivation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_derivation_created_by_id_agent"), "derivation", "agent", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_derivation_updated_by_id_agent"), "derivation", "agent", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_contribution_updated_by_id_user"), "contribution", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_contribution_created_by_id_user"), "contribution", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_contribution_updated_by_id_agent"),
        "contribution",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_contribution_created_by_id_agent"),
        "contribution",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_brain_region_hierarchy_created_by_id_user"),
        "brain_region_hierarchy",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_brain_region_hierarchy_updated_by_id_user"),
        "brain_region_hierarchy",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_brain_region_hierarchy_updated_by_id_agent"),
        "brain_region_hierarchy",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_brain_region_hierarchy_created_by_id_agent"),
        "brain_region_hierarchy",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_brain_region_updated_by_id_user"), "brain_region", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_brain_region_created_by_id_user"), "brain_region", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_brain_region_created_by_id_agent"),
        "brain_region",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_brain_region_updated_by_id_agent"),
        "brain_region",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_asset_updated_by_id_user"), "asset", type_="foreignkey")
    op.drop_constraint(op.f("fk_asset_created_by_id_user"), "asset", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_asset_updated_by_id_agent"), "asset", "agent", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_asset_created_by_id_agent"), "asset", "agent", ["created_by_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_annotation_body_updated_by_id_user"), "annotation_body", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_annotation_body_created_by_id_user"), "annotation_body", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_annotation_body_created_by_id_agent"),
        "annotation_body",
        "agent",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_annotation_body_updated_by_id_agent"),
        "annotation_body",
        "agent",
        ["updated_by_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_annotation_created_by_id_user"), "annotation", type_="foreignkey")
    op.drop_constraint(op.f("fk_annotation_updated_by_id_user"), "annotation", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_annotation_created_by_id_agent"), "annotation", "agent", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_annotation_updated_by_id_agent"), "annotation", "agent", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_agent_updated_by_id_user"), "agent", type_="foreignkey")
    op.drop_constraint(op.f("fk_agent_created_by_id_user"), "agent", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_agent_created_by_id_agent"), "agent", "agent", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_agent_updated_by_id_agent"), "agent", "agent", ["updated_by_id"], ["id"]
    )
    op.drop_constraint(op.f("fk_activity_updated_by_id_user"), "activity", type_="foreignkey")
    op.drop_constraint(op.f("fk_activity_created_by_id_user"), "activity", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_activity_updated_by_id_agent"), "activity", "agent", ["updated_by_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_activity_created_by_id_agent"), "activity", "agent", ["created_by_id"], ["id"]
    )
    op.drop_index(op.f("ix_user_pref_label"), table_name="user")
    op.drop_index(op.f("ix_user_creation_date"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
