"""Default migration message

Revision ID: 929dd74eeb5c
Revises: d9254fd8d8c1
Create Date: 2026-02-02 16:09:02.542406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "929dd74eeb5c"
down_revision: Union[str, None] = "d9254fd8d8c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ion_channel_model", sa.Column("max_permeability_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ion_channel_model", "max_permeability_name")
    # ### end Alembic commands ###
