"""Update triggers

Revision ID: 15f72ba9cf21
Revises: 5a2cf1a438ff
Create Date: 2026-06-08 14:32:32.593606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "15f72ba9cf21"
down_revision: Union[str, None] = "5a2cf1a438ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_entity_public_creation_date_id"),
        table_name="entity",
        postgresql_where="(authorized_public = true)",
    )
    op.create_index(
        "ix_entity_public_creation_date_id",
        "entity",
        ["creation_date", "id"],
        unique=False,
        postgresql_ops={"creation_date": "DESC"},
        postgresql_where=sa.text("authorized_public = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_entity_public_creation_date_id",
        table_name="entity",
        postgresql_ops={"creation_date": "DESC"},
        postgresql_where=sa.text("authorized_public = true"),
    )
    op.create_index(
        op.f("ix_entity_public_creation_date_id"),
        "entity",
        [sa.literal_column("creation_date DESC"), "id"],
        unique=False,
        postgresql_where="(authorized_public = true)",
    )
    # ### end Alembic commands ###
