"""emodel_opt_asset_labels

Revision ID: 92914b98dec8
Revises: 9e36650e03a9
Create Date: 2026-06-26 11:24:32.724618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "92914b98dec8"
down_revision: Union[str, None] = "9e36650e03a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assetlabel",
        new_values=[
            "directory_child",
            "morphology",
            "morphology_with_spines",
            "cell_composition_summary",
            "cell_composition_volumes",
            "single_neuron_synaptome_config",
            "single_neuron_synaptome_simulation_data",
            "single_neuron_simulation_data",
            "sonata_circuit",
            "compressed_sonata_circuit",
            "circuit_figures",
            "circuit_analysis_data",
            "circuit_connectivity_matrices",
            "task_result",
            "nwb",
            "neuron_hoc",
            "emodel_optimization_output",
            "emodel_optimisation_checkpoint",
            "sonata_simulation_config",
            "simulation_generation_config",
            "ion_channel_modeling_generation_config",
            "custom_node_sets",
            "campaign_generation_config",
            "campaign_summary",
            "replay_spikes",
            "voltage_report",
            "spike_report",
            "neuron_mechanisms",
            "brain_atlas_annotation",
            "brain_atlas_region_mesh",
            "voxel_densities",
            "validation_result_figure",
            "validation_result_details",
            "simulation_designer_image",
            "circuit_visualization",
            "node_stats",
            "network_stats_a",
            "network_stats_b",
            "cell_surface_mesh",
            "jupyter_notebook",
            "requirements",
            "notebook_required_files",
            "ion_channel_model_figure",
            "ion_channel_model_figure_summary_json",
            "ion_channel_model_thumbnail",
            "circuit_extraction_config",
            "skeletonization_config",
            "task_config",
            "lod_mesh_block",
            "electrode_array_weight_matrix",
            "efeature_extraction_features",
            "efeature_extraction_figures",
            "efeature_extraction_cells",
            "efeature_extraction_protocols",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="label")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assetlabel",
        new_values=[
            "directory_child",
            "morphology",
            "morphology_with_spines",
            "cell_composition_summary",
            "cell_composition_volumes",
            "single_neuron_synaptome_config",
            "single_neuron_synaptome_simulation_data",
            "single_neuron_simulation_data",
            "sonata_circuit",
            "compressed_sonata_circuit",
            "circuit_figures",
            "circuit_analysis_data",
            "circuit_connectivity_matrices",
            "task_result",
            "nwb",
            "neuron_hoc",
            "emodel_optimization_output",
            "sonata_simulation_config",
            "simulation_generation_config",
            "ion_channel_modeling_generation_config",
            "custom_node_sets",
            "campaign_generation_config",
            "campaign_summary",
            "replay_spikes",
            "voltage_report",
            "spike_report",
            "neuron_mechanisms",
            "brain_atlas_annotation",
            "brain_atlas_region_mesh",
            "voxel_densities",
            "validation_result_figure",
            "validation_result_details",
            "simulation_designer_image",
            "circuit_visualization",
            "node_stats",
            "network_stats_a",
            "network_stats_b",
            "cell_surface_mesh",
            "jupyter_notebook",
            "requirements",
            "notebook_required_files",
            "ion_channel_model_figure",
            "ion_channel_model_figure_summary_json",
            "ion_channel_model_thumbnail",
            "circuit_extraction_config",
            "skeletonization_config",
            "task_config",
            "lod_mesh_block",
            "electrode_array_weight_matrix",
            "efeature_extraction_features",
            "efeature_extraction_figures",
            "efeature_extraction_cells",
            "efeature_extraction_protocols",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="label")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
