"""Update triggers

Revision ID: 1f5cf23383af
Revises: 38e60731b8fc
Create Date: 2026-03-04 17:41:05.591001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "1f5cf23383af"
down_revision: Union[str, None] = "38e60731b8fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_task_config_task_config_description_vector = PGTrigger(
        schema="public",
        signature="task_config_description_vector",
        on_entity="public.task_config",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON task_config\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_task_config_task_config_description_vector)

    public_auth_fnc_task_config_task_config_generator_id = PGFunction(
        schema="public",
        signature="auth_fnc_task_config_task_config_generator_id()",
        definition="RETURNS TRIGGER AS $$\n            BEGIN\n                IF NEW.task_config_generator_id IS NULL THEN RETURN NEW; END IF;\n                IF NOT EXISTS (\n                    SELECT 1 FROM entity e1\n                    JOIN entity e2 ON e2.id = NEW.id\n                    WHERE e1.id = NEW.task_config_generator_id\n                    AND (e1.authorized_public = TRUE\n                        OR (e2.authorized_public = FALSE\n                            AND e1.authorized_project_id = e2.authorized_project_id\n                        )\n                    )\n                ) THEN\n                    RAISE EXCEPTION 'unauthorized private reference\\: task_config.task_config_generator_id'\n                        USING ERRCODE = '42501'; -- Insufficient Privilege\n                END IF;\n                RETURN NEW;\n            END;\n            $$ LANGUAGE plpgsql",
    )
    op.create_entity(public_auth_fnc_task_config_task_config_generator_id)

    public_task_config_auth_trg_task_config_task_config_generator_id = PGTrigger(
        schema="public",
        signature="auth_trg_task_config_task_config_generator_id",
        on_entity="public.task_config",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON task_config\n            FOR EACH ROW EXECUTE FUNCTION auth_fnc_task_config_task_config_generator_id()",
    )
    op.create_entity(public_task_config_auth_trg_task_config_task_config_generator_id)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_task_config_auth_trg_task_config_task_config_generator_id = PGTrigger(
        schema="public",
        signature="auth_trg_task_config_task_config_generator_id",
        on_entity="public.task_config",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON task_config\n            FOR EACH ROW EXECUTE FUNCTION auth_fnc_task_config_task_config_generator_id()",
    )
    op.drop_entity(public_task_config_auth_trg_task_config_task_config_generator_id)

    public_auth_fnc_task_config_task_config_generator_id = PGFunction(
        schema="public",
        signature="auth_fnc_task_config_task_config_generator_id()",
        definition="RETURNS TRIGGER AS $$\n            BEGIN\n                IF NEW.task_config_generator_id IS NULL THEN RETURN NEW; END IF;\n                IF NOT EXISTS (\n                    SELECT 1 FROM entity e1\n                    JOIN entity e2 ON e2.id = NEW.id\n                    WHERE e1.id = NEW.task_config_generator_id\n                    AND (e1.authorized_public = TRUE\n                        OR (e2.authorized_public = FALSE\n                            AND e1.authorized_project_id = e2.authorized_project_id\n                        )\n                    )\n                ) THEN\n                    RAISE EXCEPTION 'unauthorized private reference\\: task_config.task_config_generator_id'\n                        USING ERRCODE = '42501'; -- Insufficient Privilege\n                END IF;\n                RETURN NEW;\n            END;\n            $$ LANGUAGE plpgsql",
    )
    op.drop_entity(public_auth_fnc_task_config_task_config_generator_id)

    public_task_config_task_config_description_vector = PGTrigger(
        schema="public",
        signature="task_config_description_vector",
        on_entity="public.task_config",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON task_config\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_task_config_task_config_description_vector)

    # ### end Alembic commands ###
