"""Update triggers

Revision ID: 410a4832aa63
Revises: a7ff7c1259db
Create Date: 2026-08-21 13:41:30.710578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "410a4832aa63"
down_revision: Union[str, None] = "8953d8ad7437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table("_person_sub_id_mapping")

    op.execute(sql_text("""
        WITH duplicates AS (
            SELECT
                ant.id,
                ant.name || '_' || ROW_NUMBER() OVER (
                    PARTITION BY e.authorized_project_id, ant.name
                    ORDER BY e.creation_date
                ) AS new_name,
                ROW_NUMBER() OVER (
                    PARTITION BY e.authorized_project_id, ant.name
                    ORDER BY e.creation_date
                ) AS rn
            FROM analysis_notebook_template ant
            JOIN entity e ON e.id = ant.id
        )
        UPDATE analysis_notebook_template ant
        SET name = d.new_name
        FROM duplicates d
        WHERE ant.id = d.id AND d.rn > 1
    """))

    # ### commands auto generated by Alembic - please adjust! ###
    public_unique_name_fnc_analysis_notebook_template = PGFunction(
        schema="public",
        signature="unique_name_fnc_analysis_notebook_template()",
        definition="RETURNS TRIGGER AS $$\n            DECLARE\n                lock_key bigint;\n                project_id uuid;\n            BEGIN\n                SELECT authorized_project_id INTO project_id\n                FROM entity WHERE id = NEW.id;\n\n                lock_key := (\n                    ('x' || substring(md5(project_id::text || '\\:' || NEW.name), 1, 16))::bit(64)::bigint\n                ) >> 1;\n                PERFORM pg_advisory_xact_lock(lock_key);\n\n                IF EXISTS (\n                    SELECT 1 FROM entity e\n                    JOIN analysis_notebook_template t ON t.id = e.id\n                    WHERE e.authorized_project_id = project_id\n                    AND t.name = NEW.name\n                    AND t.id != NEW.id\n                ) THEN\n                    RAISE EXCEPTION 'duplicate name % in project %', NEW.name, project_id\n                        USING ERRCODE = '23505';\n                END IF;\n\n                RETURN NEW;\n            END;\n            $$ LANGUAGE plpgsql",
    )
    op.create_entity(public_unique_name_fnc_analysis_notebook_template)

    public_analysis_notebook_template_unique_name_trg_analysis_notebook_template = PGTrigger(
        schema="public",
        signature="unique_name_trg_analysis_notebook_template",
        on_entity="public.analysis_notebook_template",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE OF name ON analysis_notebook_template\n            FOR EACH ROW EXECUTE FUNCTION unique_name_fnc_analysis_notebook_template()",
    )
    op.create_entity(public_analysis_notebook_template_unique_name_trg_analysis_notebook_template)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_analysis_notebook_template_unique_name_trg_analysis_notebook_template = PGTrigger(
        schema="public",
        signature="unique_name_trg_analysis_notebook_template",
        on_entity="public.analysis_notebook_template",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE OF name ON analysis_notebook_template\n            FOR EACH ROW EXECUTE FUNCTION unique_name_fnc_analysis_notebook_template()",
    )
    op.drop_entity(public_analysis_notebook_template_unique_name_trg_analysis_notebook_template)

    public_unique_name_fnc_analysis_notebook_template = PGFunction(
        schema="public",
        signature="unique_name_fnc_analysis_notebook_template()",
        definition="RETURNS TRIGGER AS $$\n            DECLARE\n                lock_key bigint;\n                project_id uuid;\n            BEGIN\n                SELECT authorized_project_id INTO project_id\n                FROM entity WHERE id = NEW.id;\n\n                lock_key := (\n                    ('x' || substring(md5(project_id::text || '\\:' || NEW.name), 1, 16))::bit(64)::bigint\n                ) >> 1;\n                PERFORM pg_advisory_xact_lock(lock_key);\n\n                IF EXISTS (\n                    SELECT 1 FROM entity e\n                    JOIN analysis_notebook_template t ON t.id = e.id\n                    WHERE e.authorized_project_id = project_id\n                    AND t.name = NEW.name\n                    AND t.id != NEW.id\n                ) THEN\n                    RAISE EXCEPTION 'duplicate name % in project %', NEW.name, project_id\n                        USING ERRCODE = '23505';\n                END IF;\n\n                RETURN NEW;\n            END;\n            $$ LANGUAGE plpgsql",
    )
    op.drop_entity(public_unique_name_fnc_analysis_notebook_template)

    op.create_table(
        "_person_sub_id_mapping",
        sa.Column("person_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("sub_id", sa.UUID(), autoincrement=False, nullable=True),
    )

    # ### end Alembic commands ###
