"""Add create extracellular array activity and config types

Revision ID: 129ca3e7dc4e
Revises: c8cdf20bbb0d
Create Date: 2026-05-06 09:59:26.259018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "129ca3e7dc4e"
down_revision: Union[str, None] = "c8cdf20bbb0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="taskconfigtype",
        new_values=[
            "circuit_simulation__campaign",
            "circuit_simulation__config",
            "circuit_extraction__campaign",
            "circuit_extraction__config",
            "ion_channel_modeling__campaign",
            "ion_channel_modeling__config",
            "skeletonization__campaign",
            "skeletonization__config",
            "ion_channel_simulation__campaign",
            "ion_channel_simulation__config",
            "em_synapse_mapping__campaign",
            "em_synapse_mapping__config",
            "aind_ephys_preprocessing__campaign",
            "aind_ephys_preprocessing__config",
            "aind_ephys_spikesorting__campaign",
            "aind_ephys_spikesorting__config",
            "create_silico_extracellular_array__campaign",
            "create_silico_extracellular_array__config",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="task_config", column_name="task_config_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="taskactivitytype",
        new_values=[
            "circuit_simulation__config_generation",
            "circuit_simulation__execution",
            "circuit_extraction__config_generation",
            "circuit_extraction__execution",
            "ion_channel_modeling__config_generation",
            "ion_channel_modeling__execution",
            "skeletonization__config_generation",
            "skeletonization__execution",
            "ion_channel_simulation__config_generation",
            "ion_channel_simulation__execution",
            "em_synapse_mapping__config_generation",
            "em_synapse_mapping__execution",
            "aind_ephys_preprocessing__config_generation",
            "aind_ephys_preprocessing__execution",
            "aind_ephys_spikesorting__config_generation",
            "aind_ephys_spikesorting__execution",
            "create_silico_extracellular_array__config_generation",
            "create_silico_extracellular_array__execution",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="task_activity", column_name="task_activity_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="taskactivitytype",
        new_values=[
            "circuit_simulation__config_generation",
            "circuit_simulation__execution",
            "circuit_extraction__config_generation",
            "circuit_extraction__execution",
            "ion_channel_modeling__config_generation",
            "ion_channel_modeling__execution",
            "skeletonization__config_generation",
            "skeletonization__execution",
            "ion_channel_simulation__config_generation",
            "ion_channel_simulation__execution",
            "em_synapse_mapping__config_generation",
            "em_synapse_mapping__execution",
            "aind_ephys_preprocessing__config_generation",
            "aind_ephys_preprocessing__execution",
            "aind_ephys_spikesorting__config_generation",
            "aind_ephys_spikesorting__execution",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="task_activity", column_name="task_activity_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="taskconfigtype",
        new_values=[
            "circuit_simulation__campaign",
            "circuit_simulation__config",
            "circuit_extraction__campaign",
            "circuit_extraction__config",
            "ion_channel_modeling__campaign",
            "ion_channel_modeling__config",
            "skeletonization__campaign",
            "skeletonization__config",
            "ion_channel_simulation__campaign",
            "ion_channel_simulation__config",
            "em_synapse_mapping__campaign",
            "em_synapse_mapping__config",
            "aind_ephys_preprocessing__campaign",
            "aind_ephys_preprocessing__config",
            "aind_ephys_spikesorting__campaign",
            "aind_ephys_spikesorting__config",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="task_config", column_name="task_config_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
