"""Update triggers

Revision ID: c9d905433b3e
Revises: e3ccf18151c5
Create Date: 2026-06-10 15:06:30.792840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "c9d905433b3e"
down_revision: Union[str, None] = "e3ccf18151c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_task_result_task_result_description_vector = PGTrigger(
        schema="public",
        signature="task_result_description_vector",
        on_entity="public.task_result",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON task_result\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.create_entity(public_task_result_task_result_description_vector)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_task_result_task_result_description_vector = PGTrigger(
        schema="public",
        signature="task_result_description_vector",
        on_entity="public.task_result",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON task_result\n            FOR EACH ROW EXECUTE FUNCTION\n                tsvector_update_trigger(description_vector, 'pg_catalog.english', description, name)",
    )
    op.drop_entity(public_task_result_task_result_description_vector)

    # ### end Alembic commands ###
