"""s3_upload_delegation

Revision ID: ea6989325f62
Revises: 642ef45b49c6
Create Date: 2026-01-12 23:27:24.210332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "ea6989325f62"
down_revision: Union[str, None] = "642ef45b49c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset", sa.Column("upload_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assetstatus",
        new_values=["CREATED", "UPLOADING", "DELETED"],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="status")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="assetstatus",
        new_values=["CREATED", "DELETED"],
        affected_columns=[
            TableReference(table_schema="public", table_name="asset", column_name="status")
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("asset", "upload_meta")
    # ### end Alembic commands ###
