"""add number_neurons to Simulation

Revision ID: 316cadee1c4f
Revises: c0c539e43701
Create Date: 2026-01-06 09:22:49.113800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text, text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "316cadee1c4f"
down_revision: Union[str, None] = "c0c539e43701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("simulation", sa.Column("number_neurons", sa.BigInteger(), nullable=True))

    op.execute(
        text("""
        UPDATE simulation
        SET number_neurons = 1
        WHERE entity_id IN (
            SELECT id FROM entity WHERE type = 'memodel'
        )
    """)
    )

    op.execute(
        text("""
        UPDATE simulation
        SET number_neurons = circuit.number_neurons
        FROM circuit, entity
        WHERE simulation.entity_id = circuit.id
        AND simulation.entity_id = entity.id
        AND entity.type = 'circuit'
    """)
    )

    op.alter_column("simulation", "number_neurons", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation", "number_neurons")
    # ### end Alembic commands ###
