"""Add composite indexes for measurement filtering performance

Revision ID: 2c36af0528a3
Revises: a71ec2512158
Create Date: 2026-06-25 15:04:48.673059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "2c36af0528a3"
down_revision: Union[str, None] = "a71ec2512158"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_measurement_item_kind_id_name_value",
        "measurement_item",
        ["measurement_kind_id", "name", "value"],
        unique=False,
    )
    op.create_index(
        "ix_measurement_kind_annotation_id_structural_domain",
        "measurement_kind",
        ["measurement_annotation_id", "structural_domain"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_measurement_kind_annotation_id_structural_domain", table_name="measurement_kind"
    )
    op.drop_index("ix_measurement_item_kind_id_name_value", table_name="measurement_item")
    # ### end Alembic commands ###
