"""Make nullable attributes in EMDenseReconstructionDataset

Revision ID: 642ef45b49c6
Revises: 316cadee1c4f
Create Date: 2026-01-09 17:47:49.539777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "642ef45b49c6"
down_revision: Union[str, None] = "316cadee1c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "em_dense_reconstruction_dataset", "release_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "cave_client_url",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "cave_datastack",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "precomputed_mesh_url",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "cell_identifying_property",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "cell_identifying_property",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "precomputed_mesh_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "cave_datastack",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset",
        "cave_client_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "em_dense_reconstruction_dataset", "release_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
