"""orcid_rorid

Revision ID: b26853460669
Revises: 92914b98dec8
Create Date: 2026-06-30 19:00:00.374608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from sqlalchemy import Text
import app.db.types

# revision identifiers, used by Alembic.
revision: str = "b26853460669"
down_revision: Union[str, None] = "92914b98dec8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("ror_id", sa.String(length=25), nullable=True))
    op.create_index(op.f("ix_organization_ror_id"), "organization", ["ror_id"], unique=True)
    op.add_column("person", sa.Column("orcid", sa.String(length=37), nullable=True))
    op.create_index(op.f("ix_person_orcid"), "person", ["orcid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_person_orcid"), table_name="person")
    op.drop_column("person", "orcid")
    op.drop_index(op.f("ix_organization_ror_id"), table_name="organization")
    op.drop_column("organization", "ror_id")
    # ### end Alembic commands ###
