---
name: security checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install requirements
        run: make install
      - name: pip audit
        run: |
          uv run --all-groups --with pip-audit pip-audit -l > intermediate.txt 2>&1
          tail -n +7 intermediate.txt > audit.txt
          cat audit.txt
      - name: Comment with audit result
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: audit.txt
